// domain
export const DOMAIN = "http://localhost:3001";

export const LIMIT_CUS = 30;
export const LIMIT_ADM = 6;
//link image
export const LINK_IMAGE = DOMAIN + "/images/productImages/"
// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = { "Content-Type": "Application/json" }

// types of actions
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE"

export const GET_SUGGEST_REQUEST = "GET_SUGGEST_REQUEST"
export const GET_SUGGEST_SUCCESS = "GET_SUGGEST_SUCCESS"
export const GET_SUGGEST_FAILURE = "GET_SUGGEST_FAILURE"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE"

export const CHANGE_PAGE_REQUEST = "CHANGE_PAGE_REQUEST"
export const CHANGE_PAGE_SUCCESS = "CHANGE_PAGE_SUCCESS"
export const CHANGE_PAGE_FAILURE = "CHANGE_PAGE_FAILURE"

export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST"
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS"
export const GET_COLLECTION_FAILURE = "GET_COLLECTION_FAILURE"

export const GET_FEATURE_REQUEST = "GET_FEATURE_REQUEST"
export const GET_FEATURE_SUCCESS = "GET_FEATURE_SUCCESS"
export const GET_FEATURE_FAILURE = "GET_FEATURE_FAILURE"

export const GET_MATERIAL_REQUEST = "GET_MATERIAL_REQUEST"
export const GET_MATERIAL_SUCCESS = "GET_MATERIAL_SUCCESS"
export const GET_MATERIAL_FAILURE = "GET_MATERIAL_FAILURE"

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE"


export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE"

export const GET_PRODUCT_FOR_BASKET_REQUEST = "GET_PRODUCT_FOR_BASKET_REQUEST"
export const GET_PRODUCT_FOR_BASKET_SUCCESS = "GET_PRODUCT_FOR_BASKET_SUCCESS"
export const GET_PRODUCT_FOR_BASKET_FAILURE = "GET_PRODUCT_FOR_BASKET_FAILURE"

export const DISPATCH_PRODUCT_FOR_BASKET_REQUEST = "DISPATCH_PRODUCT_FOR_BASKET_REQUEST"


export const ADD_BILL_REQUEST = "ADD_BILL_REQUEST"
export const ADD_BILL_SUCCESS = "ADD_BILL_SUCCESS"
export const ADD_BILL_FAILURE = "ADD_BILL_FAILURE"

export const GET_BILL_REQUEST = "GET_BILL_REQUEST"
export const GET_BILL_SUCCESS = "GET_BILL_SUCCESS"
export const GET_BILL_FAILURE = "GET_BILL_FAILURE"

